version: "3"

services:
    nginx:
        build:
            context: docker/dev/nginx
        ports:
            - 8080:80
        volumes:
            - ./app:/app
        depends_on:
            - php
    php:
        build:
            context: docker/dev/php
        volumes:
            - ./app:/app
