version: "3"

services:
    nginx:
        build:
            context: docker/dev/nginx
        ports:
            - 8080:80
        volumes:
            - ./app:/app
        depends_on:
            - php
    php:
        build:
            context: docker/dev/php
        volumes:
            - ./app:/app
        depends_on:
            - db
    db:
        # image: mysql # 546 Mb
        image: mariadb # 401 Mb
        restart: always
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

volumes:
    mysql-data:
